spring:
  application:
    name: company
  datasource:
    url: jdbc:postgresql://localhost:5432/pgcompany
    username: adminqa
    password: qa123456
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
